
app: java-app
containerArgs: ' '
cpuLimit: 500m
cpuRequest: 300m
environment: dev
image: ghcr.io/cse-labs/java-app:latest
ingressPrefix: /java-app/
livenessProbe: /java-app/healthz
memoryLimit: 512Mi
memoryRequest: 512Mi
namespace: java-app
nodePort: {{nodePort}}
port: 8080
readinessProbe: /java-app/readyz
targets: []
template: pib-service