#!/bin/bash

# name: ns
# short: Get the namespaces on the local dev cluster

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

hdrsort()
{
    read -r
    printf "%s\\n" "$REPLY"
    sort
}

kubectl get ns | hdrsort
