#!/bin/bash

# name: pods
# short: Get all pods on the local dev cluster

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

hdrsort()
{
    read -r
    printf "%s\\n" "$REPLY"
    sort
}

kubectl get pods -A | hdrsort
