#!/bin/bash

# get path to k3d.yaml
k3d="$(dirname "$(which kic)")/.kic/k3d.yaml"

# validate k3d.yaml
if [ ! -f "$k3d" ]
then
    echo "File not found - $k3d"
    exit 0
fi

kic cluster delete

echo ""
echo "Creating cluster ..."

k3d cluster create \
    --registry-use k3d-registry.localhost:5500 \
    --k3s-server-arg '--no-deploy=traefik' \
    --config "$k3d"
