#!/bin/bash

cd "$PIB_BASE/java-app" || exit

if [ ! -d deploy/app ]
then
    echo "$PWD/deploy/app/app directory not found"
    exit 0
fi


# delete local deployment
kubectl delete -f deploy/app/app --ignore-not-found=true --wait=false

kic build java-app

# deploy local app and re-deploy webv
kubectl apply -f deploy/app
kubectl apply -R -f deploy/app/app
