#!/bin/bash

cd "$PIB_BASE/java-app" || exit

if [ ! -d deploy/monitoring ]
then
    echo "$PWD/deploy/monitoring directory not found"
    exit 0
fi

# create deployment from webv-local
kubectl apply -f deploy/monitoring
kubectl apply -R -f deploy/monitoring
