#!/bin/bash

cd "$PIB_BASE/java-app" || exit

if [ ! -d deploy/app/webv ]
then
    echo "$PWD/deploy/app/webv directory not found"
    exit 0
fi

# delete local deployment
kubectl delete -f deploy/app/webv --ignore-not-found=true --wait=false

kic build webv

# create deployment from webv-local
kubectl apply -f deploy/app
kubectl apply -f deploy/app/webv
