#!/bin/bash

#name: all
#short: Run all status checks on the local cluster

echo "Checking Heartbeat"
kic check heartbeat

echo "Checking Java-App"
kic check java-app

echo "Checking WebV"
kic check webv

echo "Checking Grafana"
kic check grafana

echo "Checking Prometheus"
kic check prometheus
