name: Docker-Build

on:
  workflow_dispatch:
  push:
    paths:
    - 'java-app/Dockerfile'
    - 'java-app/pom.xml'
    - 'java-app/src/**.properties'
    - 'java-app/src/**.java'
    - '.github/workflows/docker-build.yaml'

jobs:

  build:

    env:
      DOCKER_REPO: $PIB_GHCR/java-app

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_ID }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker pull
      run: |
        docker pull azul/zulu-openjdk-alpine:11.0.10
        docker pull azul/zulu-openjdk-alpine:11.0.10-jre 

    - name: Docker Build
      run: |
        docker build java-app -t image

    - name: Docker Tag and Push
      run: |
        # VERSION=$(docker run --rm image --version)

        # tag the repo with :latest
        docker tag image $DOCKER_REPO:latest

        # Push to the repo
        docker push -a $DOCKER_REPO
